export type ProductoDemo = {
  nombre: string;
  categoria: string;
  marca: string;
  presentacion: string;
  origen: string;
  proveedores: number;
  disponible: number;
  descripcion: string;
};

export const productosDemo: ProductoDemo[] = [
  {
    nombre: 'Guantes de nitrilo no esteril',
    categoria: 'Proteccion personal',
    marca: 'SafeTouch',
    presentacion: 'Caja x 100 unidades',
    origen: 'Malasia',
    proveedores: 2,
    disponible: 1,
    descripcion:
      'Producto de uso hospitalario. Caja x 100 unidades. Registro completo preparado.',
  },
  {
    nombre: 'Guantes quirurgicos esteriles',
    categoria: 'Proteccion personal',
    marca: 'SterilPro',
    presentacion: 'Caja x 50 pares',
    origen: 'Alemania',
    proveedores: 3,
    disponible: 1,
    descripcion:
      'Producto de uso hospitalario. Caja x 50 pares. Registro completo preparado.',
  },
  {
    nombre: 'Mascarilla quirurgica triple capa',
    categoria: 'Proteccion personal',
    marca: 'MediCare',
    presentacion: 'Caja x 50 unidades',
    origen: 'China',
    proveedores: 2,
    disponible: 1,
    descripcion:
      'Producto de uso hospitalario. Caja x 50 unidades. Registro completo preparado.',
  },
  {
    nombre: 'Respirador N95',
    categoria: 'Proteccion personal',
    marca: 'CarePlus',
    presentacion: 'Caja x 20 unidades',
    origen: 'China',
    proveedores: 3,
    disponible: 2,
    descripcion:
      'Producto de uso hospitalario. Caja x 20 unidades. Registro completo preparado.',
  },
  {
    nombre: 'Jeringa descartable 5 ml',
    categoria: 'Material descartable',
    marca: 'BolMed',
    presentacion: 'Caja x 100 unidades',
    origen: 'Bolivia',
    proveedores: 2,
    disponible: 1,
    descripcion:
      'Producto de uso hospitalario. Caja x 100 unidades. Registro completo preparado.',
  },
  {
    nombre: 'Jeringa descartable 10 ml',
    categoria: 'Material descartable',
    marca: 'BolMed',
    presentacion: 'Caja x 100 unidades',
    origen: 'Bolivia',
    proveedores: 3,
    disponible: 1,
    descripcion:
      'Producto de uso hospitalario. Caja x 100 unidades. Registro completo preparado.',
  },
  {
    nombre: 'Equipo de venoclisis macrogotero',
    categoria: 'Material descartable',
    marca: 'LifeLine',
    presentacion: 'Paquete x 25 unidades',
    origen: 'Mexico',
    proveedores: 2,
    disponible: 1,
    descripcion:
      'Producto de uso hospitalario. Paquete x 25 unidades. Registro completo preparado.',
  },
  {
    nombre: 'Cateter intravenoso 20G',
    categoria: 'Material descartable',
    marca: 'MediCare',
    presentacion: 'Caja x 50 unidades',
    origen: 'Estados Unidos',
    proveedores: 3,
    disponible: 2,
    descripcion:
      'Producto de uso hospitalario. Caja x 50 unidades. Registro completo preparado.',
  },
  {
    nombre: 'Gasa esteril 10 x 10 cm',
    categoria: 'Curacion y heridas',
    marca: 'SterilPro',
    presentacion: 'Caja x 100 sobres',
    origen: 'Alemania',
    proveedores: 2,
    disponible: 1,
    descripcion:
      'Producto de uso hospitalario. Caja x 100 sobres. Registro completo preparado.',
  },
  {
    nombre: 'Venda elastica 10 cm',
    categoria: 'Curacion y heridas',
    marca: 'CarePlus',
    presentacion: 'Paquete x 12 rollos',
    origen: 'China',
    proveedores: 3,
    disponible: 1,
    descripcion:
      'Producto de uso hospitalario. Paquete x 12 rollos. Registro completo preparado.',
  },
  {
    nombre: 'Aspirador quirurgico portatil',
    categoria: 'Instrumental quirurgico',
    marca: 'Surgimax',
    presentacion: 'Unidad',
    origen: 'Pakistan',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Equipo portatil para procedimientos clinicos y quirurgicos.',
  },
  {
    nombre: 'Camilla de transporte hidraulica',
    categoria: 'Higiene hospitalaria',
    marca: 'CarePlus',
    presentacion: 'Unidad',
    origen: 'China',
    proveedores: 3,
    disponible: 1,
    descripcion: 'Camilla hospitalaria de transporte con sistema hidraulico.',
  },
  {
    nombre: 'Tubo al vacio tapa lila 4 ml',
    categoria: 'Laboratorio',
    marca: 'AndesLab',
    presentacion: 'Caja x 100 unidades',
    origen: 'Bolivia',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Tubo para muestras clinicas de laboratorio.',
  },
  {
    nombre: 'Tubo al vacio tapa roja 6 ml',
    categoria: 'Laboratorio',
    marca: 'AndesLab',
    presentacion: 'Caja x 100 unidades',
    origen: 'Bolivia',
    proveedores: 3,
    disponible: 1,
    descripcion: 'Tubo para muestras clinicas de laboratorio.',
  },
  {
    nombre: 'Prueba rapida de embarazo hCG',
    categoria: 'Laboratorio',
    marca: 'Bioscan',
    presentacion: 'Caja x 25 pruebas',
    origen: 'Corea del Sur',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Prueba rapida para diagnostico clinico.',
  },
  {
    nombre: 'Alcohol medicinal 70%',
    categoria: 'Higiene hospitalaria',
    marca: 'Hospiclean',
    presentacion: 'Bidon de 5 litros',
    origen: 'Brasil',
    proveedores: 3,
    disponible: 1,
    descripcion: 'Solucion para limpieza y desinfeccion hospitalaria.',
  },
  {
    nombre: 'Desinfectante de alto nivel',
    categoria: 'Higiene hospitalaria',
    marca: 'Hospiclean',
    presentacion: 'Galon de 4 litros',
    origen: 'Brasil',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Desinfectante concentrado para superficies clinicas.',
  },
  {
    nombre: 'Gel antibacterial 70%',
    categoria: 'Higiene hospitalaria',
    marca: 'Hospiclean',
    presentacion: 'Caja x 12 frascos',
    origen: 'Brasil',
    proveedores: 3,
    disponible: 1,
    descripcion: 'Gel antibacterial para uso hospitalario.',
  },
  {
    nombre: 'Cilindro de oxigeno medicinal 10 m3',
    categoria: 'Oxigenoterapia',
    marca: 'Oxylife',
    presentacion: 'Cilindro recargable',
    origen: 'Bolivia',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Cilindro de oxigeno medicinal recargable.',
  },
  {
    nombre: 'Mascarilla de oxigeno adulto',
    categoria: 'Oxigenoterapia',
    marca: 'LifeLine',
    presentacion: 'Paquete x 25 unidades',
    origen: 'Mexico',
    proveedores: 3,
    disponible: 1,
    descripcion: 'Mascarilla para administracion de oxigeno.',
  },
  {
    nombre: 'Tijera Mayo recta 17 cm',
    categoria: 'Instrumental quirurgico',
    marca: 'Surgimax',
    presentacion: 'Unidad',
    origen: 'Pakistan',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Instrumental quirurgico en acero inoxidable.',
  },
  {
    nombre: 'Pinza Kelly curva 14 cm',
    categoria: 'Instrumental quirurgico',
    marca: 'Surgimax',
    presentacion: 'Unidad',
    origen: 'Pakistan',
    proveedores: 3,
    disponible: 1,
    descripcion: 'Instrumental quirurgico en acero inoxidable.',
  },
  {
    nombre: 'Sonda Foley 16FR',
    categoria: 'Material descartable',
    marca: 'MediCare',
    presentacion: 'Caja x 10 unidades',
    origen: 'China',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Sonda descartable para procedimiento hospitalario.',
  },
  {
    nombre: 'Bata quirurgica descartable',
    categoria: 'Proteccion personal',
    marca: 'SafeTouch',
    presentacion: 'Paquete x 10 unidades',
    origen: 'Malasia',
    proveedores: 3,
    disponible: 2,
    descripcion: 'Bata descartable para proteccion en sala.',
  },
  {
    nombre: 'Campo quirurgico esteril',
    categoria: 'Curacion y heridas',
    marca: 'SterilPro',
    presentacion: 'Caja x 50 unidades',
    origen: 'Alemania',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Campo esteril para procedimientos clinicos.',
  },
  {
    nombre: 'Termometro digital clinico',
    categoria: 'Equipamiento medico',
    marca: 'CarePlus',
    presentacion: 'Unidad',
    origen: 'China',
    proveedores: 3,
    disponible: 1,
    descripcion: 'Termometro digital para control de pacientes.',
  },
  {
    nombre: 'Tensiometro aneroide adulto',
    categoria: 'Equipamiento medico',
    marca: 'MediCare',
    presentacion: 'Unidad',
    origen: 'Estados Unidos',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Equipo para medicion de presion arterial.',
  },
  {
    nombre: 'Oximetro de pulso digital',
    categoria: 'Equipamiento medico',
    marca: 'Bioscan',
    presentacion: 'Unidad',
    origen: 'Corea del Sur',
    proveedores: 3,
    disponible: 1,
    descripcion: 'Equipo portatil para saturacion de oxigeno.',
  },
  {
    nombre: 'Bolsa recolectora de orina',
    categoria: 'Material descartable',
    marca: 'LifeLine',
    presentacion: 'Paquete x 20 unidades',
    origen: 'Mexico',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Bolsa esteril para recoleccion hospitalaria.',
  },
  {
    nombre: 'Set de sutura nylon 3-0',
    categoria: 'Instrumental quirurgico',
    marca: 'Surgimax',
    presentacion: 'Caja x 24 unidades',
    origen: 'Pakistan',
    proveedores: 3,
    disponible: 1,
    descripcion: 'Set de sutura para procedimientos menores.',
  },
  {
    nombre: 'Algodon hidrofilo 500 g',
    categoria: 'Curacion y heridas',
    marca: 'BolMed',
    presentacion: 'Paquete de 500 g',
    origen: 'Bolivia',
    proveedores: 2,
    disponible: 2,
    descripcion: 'Algodon para curacion y limpieza clinica.',
  },
  {
    nombre: 'Solucion fisiologica 1000 ml',
    categoria: 'Material descartable',
    marca: 'BolMed',
    presentacion: 'Caja x 12 unidades',
    origen: 'Bolivia',
    proveedores: 3,
    disponible: 1,
    descripcion: 'Solucion fisiologica esteril para uso hospitalario.',
  },
];

export const serviciosDemo: ProductoDemo[] = [
  {
    nombre: 'Consulta medica general',
    categoria: 'Consulta externa',
    marca: 'Medicina general',
    presentacion: 'Por consulta',
    origen: 'Clinica',
    proveedores: 1,
    disponible: 1,
    descripcion: 'Atencion medica general para pacientes ambulatorios.',
  },
  {
    nombre: 'Consulta de especialidad',
    categoria: 'Consulta externa',
    marca: 'Especialidades',
    presentacion: 'Por consulta',
    origen: 'Clinica',
    proveedores: 4,
    disponible: 1,
    descripcion: 'Atencion programada con medico especialista.',
  },
  {
    nombre: 'Analisis de laboratorio basico',
    categoria: 'Laboratorio',
    marca: 'Laboratorio clinico',
    presentacion: 'Perfil basico',
    origen: 'Interno',
    proveedores: 1,
    disponible: 1,
    descripcion: 'Procesamiento de pruebas clinicas de rutina.',
  },
  {
    nombre: 'Ecografia abdominal',
    categoria: 'Imagenologia',
    marca: 'Diagnostico por imagen',
    presentacion: 'Por estudio',
    origen: 'Clinica',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Estudio ecografico de la region abdominal.',
  },
  {
    nombre: 'Rayos X digital',
    categoria: 'Imagenologia',
    marca: 'Radiologia',
    presentacion: 'Por placa',
    origen: 'Clinica',
    proveedores: 2,
    disponible: 1,
    descripcion: 'Estudio radiologico digital con informe medico.',
  },
  {
    nombre: 'Curacion ambulatoria',
    categoria: 'Procedimientos',
    marca: 'Enfermeria',
    presentacion: 'Por procedimiento',
    origen: 'Clinica',
    proveedores: 1,
    disponible: 1,
    descripcion: 'Curacion y control de heridas en consultorio.',
  },
  {
    nombre: 'Aplicacion de medicamento',
    categoria: 'Procedimientos',
    marca: 'Enfermeria',
    presentacion: 'Por aplicacion',
    origen: 'Clinica',
    proveedores: 1,
    disponible: 1,
    descripcion: 'Administracion de medicamento segun indicacion medica.',
  },
  {
    nombre: 'Internacion por dia',
    categoria: 'Hospitalizacion',
    marca: 'Hospitalizacion',
    presentacion: 'Dia cama',
    origen: 'Clinica',
    proveedores: 1,
    disponible: 1,
    descripcion: 'Servicio de estancia y cuidados hospitalarios.',
  },
  { nombre: 'Consulta pediatrica', categoria: 'Consulta externa', marca: 'Pediatria', presentacion: 'Por consulta', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Atencion medica integral para pacientes pediatricos.' },
  { nombre: 'Consulta ginecologica', categoria: 'Consulta externa', marca: 'Ginecologia', presentacion: 'Por consulta', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Valoracion y seguimiento ginecologico.' },
  { nombre: 'Consulta cardiologica', categoria: 'Consulta externa', marca: 'Cardiologia', presentacion: 'Por consulta', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Evaluacion especializada cardiovascular.' },
  { nombre: 'Electrocardiograma', categoria: 'Diagnostico', marca: 'Cardiologia', presentacion: 'Por estudio', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Registro y lectura de actividad electrica cardiaca.' },
  { nombre: 'Ecografia obstetrica', categoria: 'Imagenologia', marca: 'Diagnostico por imagen', presentacion: 'Por estudio', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Control ecografico durante el embarazo.' },
  { nombre: 'Tomografia computarizada', categoria: 'Imagenologia', marca: 'Radiologia', presentacion: 'Por estudio', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Estudio tomografico con informe medico.' },
  { nombre: 'Resonancia magnetica', categoria: 'Imagenologia', marca: 'Radiologia', presentacion: 'Por estudio', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Estudio por resonancia magnetica.' },
  { nombre: 'Perfil lipido completo', categoria: 'Laboratorio', marca: 'Laboratorio clinico', presentacion: 'Perfil', origen: 'Interno', proveedores: 1, disponible: 1, descripcion: 'Determinacion de colesterol y trigliceridos.' },
  { nombre: 'Hemograma completo', categoria: 'Laboratorio', marca: 'Laboratorio clinico', presentacion: 'Por prueba', origen: 'Interno', proveedores: 1, disponible: 1, descripcion: 'Analisis hematologico de rutina.' },
  { nombre: 'Prueba de glucosa', categoria: 'Laboratorio', marca: 'Laboratorio clinico', presentacion: 'Por prueba', origen: 'Interno', proveedores: 1, disponible: 1, descripcion: 'Determinacion de glucosa en sangre.' },
  { nombre: 'Perfil tiroideo', categoria: 'Laboratorio', marca: 'Laboratorio clinico', presentacion: 'Perfil', origen: 'Interno', proveedores: 1, disponible: 1, descripcion: 'Analisis hormonal tiroideo.' },
  { nombre: 'Nebulizacion', categoria: 'Procedimientos', marca: 'Enfermeria', presentacion: 'Por sesion', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Administracion terapeutica por nebulizacion.' },
  { nombre: 'Sutura simple', categoria: 'Procedimientos', marca: 'Emergencias', presentacion: 'Por procedimiento', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Cierre de herida menor bajo evaluacion medica.' },
  { nombre: 'Retiro de puntos', categoria: 'Procedimientos', marca: 'Enfermeria', presentacion: 'Por procedimiento', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Retiro y control de puntos de sutura.' },
  { nombre: 'Atencion de emergencia', categoria: 'Emergencias', marca: 'Emergencias', presentacion: 'Por atencion', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Valoracion y estabilizacion inicial de emergencia.' },
  { nombre: 'Traslado en ambulancia', categoria: 'Emergencias', marca: 'Ambulancia', presentacion: 'Por traslado', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Traslado asistido de paciente.' },
  { nombre: 'Fisioterapia respiratoria', categoria: 'Rehabilitacion', marca: 'Fisioterapia', presentacion: 'Por sesion', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Sesion de rehabilitacion respiratoria.' },
  { nombre: 'Fisioterapia motora', categoria: 'Rehabilitacion', marca: 'Fisioterapia', presentacion: 'Por sesion', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Sesion de recuperacion motora.' },
  { nombre: 'Habitacion privada por dia', categoria: 'Hospitalizacion', marca: 'Hospitalizacion', presentacion: 'Dia cama', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Estancia en habitacion privada con cuidados basicos.' },
  { nombre: 'Uso de quirofano', categoria: 'Cirugia', marca: 'Quirofano', presentacion: 'Por procedimiento', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Uso de sala quirurgica y equipamiento basico.' },
  { nombre: 'Control postoperatorio', categoria: 'Cirugia', marca: 'Quirofano', presentacion: 'Por consulta', origen: 'Clinica', proveedores: 1, disponible: 1, descripcion: 'Seguimiento clinico posterior a procedimiento quirurgico.' },
];
